name: ci-runner
run-name: ${{ github.actor }} is running ci-runner
on: [push, pull_request]
jobs:
  ci-runner:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
        python-version: ["3.9"]
        runnernum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        exclude:
          - os: macos-latest
            python-version: "3.9"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_test.txt
      - name: Run tests
        run: pytest tests
      - name: Run type checker
        run: python -m mypy --config-file mypy.ini -p ethstaker_deposit
      - name: Run linter
        run: flake8 --config=flake8.ini ./ethstaker_deposit ./tests
